### PR TITLE
Added repeating keyboard actions

### LINKED ISSUE #4: How will MMKBD get the current KeyState?
If I understand correctly this is a current goal:
`//TODO: repeat pressed keys`,
when passthrough is enabled.
I don't even know if this should be a goal, because the autorepeat when you press down a key, only comes from the driver, good explained in this [post](https://autohotkey.com/board/topic/98644-how-to-auto-repeat-a-remapped-key/). Anyway to achieve something like this, you will probably need to get the current KeyState. There already is a [npm package](https://www.npmjs.com/package/asynckeystate) for this, but it would need VK Keycodes to be added. Another way would be to keep track of the KeyStates just with the KBDEvents, inside of MMKBD.

### PR DESCRIPTION
**Pull request by KGT1**
Draft.
Fixes #4
Added the repeating Keystrokes.

It now manully goes up and down
```
SendInput({type:1 as 1,val:handled,up:true});
SendInput({type:1 as 1,val:handled,up:false});
```
However I dont think this solution is ideal, because it cause other keys to stutter(ex BackSpace).

### CODE REVIEW

**Comment by lal12** [comment]
Hmm I guess this won't work as intended, since many programs actually listen to the up/down event which would also be repeated in this case and might cause unwanted behavior.

I am pretty sure there is a correct solution to that, I will look into that the next days.

**Comment by KGT1** [comment]
ok the last update should fix the stuttering the key is never taken up now.

**Comment by KGT1** [comment]
Another Issue I noticed.
This only happens if you press the keys after one another.
If you press the buttons at the same time then the intentional behavior happens
gitISSUE

**Comment by KGT1** [comment]
Closing this then when you come up with a better solution

**Pull request closed without merging**
